window_padding_width 5
# hide_window_decorations yes
background_opacity 0.95
font_family CaskaydiaMono Nerd Font
font_size 14
remember_window_size no
confirm_os_window_close 0
shell fish
cursor_trail 1
cursor_shape beam
shell_integration no-cursor
remember_window_size yes

linux_display_server x11
# BEGIN_KITTY_THEME
# OneDark-Pro
include current-theme.conf
# END_KITTY_THEME
